### ISSUE TITLE
"Object of type bytes is not JSON serializable"

### ISSUE THREAD

**Issue by simonw** [eyeseast/datasette-geojson#16]
Got this error here:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/9599/206967710-74f55c31-d28a-43d0-baab-4ccfa9a71ef1.png">

A couple of options:

- It could skip outputting binary columns entirely, replacing them with a "Binary: xxx bytes" message, as seen below
- It could output them as base64, which is what Datasette does usually: https://latest.datasette.io/fixtures/binary_data.json

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/9599/206967780-8df9737e-d020-4b9c-8356-82925f678339.png">

**Comment by eyeseast** [comment]
Weird. I wonder if it's interacting with datasette-render-binary somehow.

**Comment by eyeseast** [comment]
Actually, realizing I misread your note here. I think following Datasette's handling makes the most sense here. It's the easiest way to see what's happening.
