### ISSUE TITLE
geometry column is case-sensitive

### ISSUE THREAD

**Issue by simonw** [eyeseast/datasette-geojson#19]
Just noticed that `select GEOMETRY` doesn't produce `.geojson` link but `select geometry` does.

**Comment by simonw** [comment]
https://github.com/eyeseast/datasette-geojson/blob/030bff9df89612019ec7fe24d335608ccf74b01b/datasette_geojson/__init__.py#L37-L41

**Comment by mroswell** [comment]
Wow, that was fast. Thanks!
