### ISSUE TITLE
Can I parse spatialite's geometry blob in Python?

### ISSUE THREAD

**Issue by eyeseast** [eyeseast/datasette-geojson#5]
Details on it here: https://www.gaia-gis.it/gaia-sins/BLOB-Geometry.html. It is weird.

If I could parse that, it would make working with spatialite much simpler and eliminate the need to use `AsGeoJSON()` in queries.

**Comment by simonw** [comment]
I'm pretty sure this will work:
```python
geojson = conn.execute("select AsGeoJSON(:b)", {"b": blob}).fetchone()[0]
```
Basically round-tripping that binary bytes object you got back from the `geometry` column back through a SQL query that doesn't touch any tables but uses the `AsGeoJSON` function in SpatiaLite to turn it into JSON.
