### ISSUE TITLE
Feature request: at least one bullet point in the release notes

### ISSUE THREAD

**Issue by simonw** [eyeseast/datasette-geojson#9]
Inspired by this plugin today I finally upgraded https://datasette.io/ to start listing plugins written by other people: https://github.com/simonw/datasette.io/issues/56

Here's the new page for this plugin: https://datasette.io/plugins/datasette-geojson

Just one tiny catch: the site publishes recent releases on the homepage, and expects the release notes to have at least one bullet point of text to display - but the release notes for https://github.com/eyeseast/datasette-geojson/releases/tag/v0.3.0 are missing that content, so the site homepage looks like this:

<img width="1131" alt="Banners_and_Alerts_and_Datasette__An_open_source_multi-tool_for_exploring_and_publishing_data" src="https://user-images.githubusercontent.com/9599/121796500-54b85480-cbce-11eb-9a55-da4914d9382e.png">

If you add some release notes to the tag they should show up next time I deploy the site!

**Comment by eyeseast** [comment]
Ha! I can add a bullet point. Just one though. It's a small release.
